dev/django_onlineshop/cart/urls.py
from django.urls import path
from . import views

app_name ='cart'
urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<product_id>/',views.cart_add,name='cart_add'),
    path('remove/<product_id>/',views.cart_remove,name='cart_remove'),
    path('clear/',views.cart_clear,name='cart_clear'),

]

dev/django_onlineshop/mysite/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('shop:product_list'),
         name='root'),  # 간단한 함수일 때, lamda식으로 표현
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('coupons/', include('coupons.urls')),
    path('orders/', include('orders.urls')),
    path('qna/', include('qna.urls')),
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.insert(0, path('__debug__/', include(debug_toolbar.urls)))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dev/django_onlineshop/qna/urls.py
from django.urls import path
from django.urls.base import reverse_lazy
from django.views.generic import UpdateView, DeleteView
from . import views
from .models import Question, Answer
from .forms import QuestionForm

app_name = 'qna'
urlpatterns = [
    path('add/', views.qna_add, name='add'),
    path('<pk>/update/', UpdateView.as_view(model=Question, form_class=QuestionForm), name='update'),
    path('<pk>/delete/', DeleteView.as_view(model=Question, success_url=reverse_lazy('qna:list')), name='remove'),
    path('', views.qna_list, name='list'),
    path('<id>/', views.qna_detail, name='detail'),
]

dev/django_onlineshop/templates/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}E-Commerce{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">

    {% block script %}
    {% endblock %}
</head>
<body>
    <div id="header">
        <a href="{% url 'root' %}" class="logo">HOME</a>
        <div class="text-right">
            {% if not user.is_authenticated %}

                <a href="{% url 'signup' %}">회원가입 | </a>
                <a href="{% url 'login' %}"> 로그인 | </a>
            {% else %}
                {% if user.is_superuser%}
                    <a href="/admin/"> admin | </a>
                {% endif %}
                
                    <a href="{% url 'logout' %}"> 로그아웃 | </a>
            {% endif %}    

             <a href="{% url 'qna:list' %}"> Q & A</a>    
        </div>
    </div>
  
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    장바구니 : 
                    <a href="{% url 'cart:cart_detail' %}">
                        {{ total_items }}개 상품 / {{ cart.get_total_price|intcomma}}원 
                    </a>
                {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>