dev/django_onlineshop/mysite/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('shop:product_list'),
         name='root'),  # 간단한 함수일 때, lamda식으로 표현
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('coupons/', include('coupons.urls')),
    path('orders/', include('orders.urls')),
    path('qna/', include('qna.urls')),
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.insert(0, path('__debug__/', include(debug_toolbar.urls)))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dev/django_onlineshop/qna/urls.py
from django.urls import path
from django.urls.base import reverse_lazy
from django.views.generic import UpdateView, DeleteView
from . import views
from .models import Question, Answer
from .forms import QuestionForm

app_name = 'qna'
urlpatterns = [
    path('add/', views.qna_add, name='add'),
    path('<pk>/update/', UpdateView.as_view(model=Question, form_class=QuestionForm), name='update'),
    path('<pk>/delete/', DeleteView.as_view(model=Question, success_url=reverse_lazy('qna:list')), name='remove'),
    path('', views.qna_list, name='list'),
    path('<id>/', views.qna_detail, name='detail'),
]

dev/django_onlineshop/qna/models.py
from django.db import DefaultConnectionProxy, models
from django.conf import settings
from django.urls import reverse
from shop.models import Product

class Question(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, verbose_name='제목')
    content = models.TextField(verbose_name='질문')
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)
  
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("qna:detail", kwargs={"id": self.id})
    

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField(verbose_name='답변')
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

dev/django_onlineshop/qna/forms.py
from django import forms
from .models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'content']

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = '__all__'

dev/django_onlineshop/qna/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Question, Answer
from .forms import QuestionForm, AnswerForm

def qna_list(request):
    question_list = Question.objects.all()
    return render(request,'qna/list.html',{'question_list':question_list,})

def qna_detail(request, id):
    question = get_object_or_404(Question, id=id)
    form = QuestionForm(instance=question)
    answer_list = question.answer_set.all()
    return render(request,'qna/detail.html',{'form':form, 'answer_list':answer_list})

@login_required
def qna_add(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.user = request.user
            question.save()
            return redirect('qna:list')
    else:
        form = QuestionForm()
    return render(request, 'qna/question_form.html', {'form':form})

dev/django_onlineshop/qna/templates/qna/detail.html
{% extends "base.html" %}

{% block title %}
    Q&A
{% endblock %}

{% block  content %}
    <h1>Question</h1>
        <table class="qna">
            <tr>
                <td>
                    {{form.as_p}}
                </td>
            </tr>
        </table>

    <h1>Answer</h1>
    {% if answer_list %}
        {% for answer in answer_list%}
                {{answer.content}} <br>
        {% endfor%}
    {% else %}
        빠르게 답변 드리겠습니다
    {% endif %}
    

{% endblock %}

dev/django_onlineshop/qna/templates/qna/list.html
{% extends "base.html" %}

{% block title %}
    Q&A
{% endblock %}

{% block content %}
    <h1>Q&A</h1>
    <div class="text-right">
        <a href="{% url 'qna:add' %}">글쓰기</a>
    </div>
    <table class="cart">
        <thead>
            <tr>
                <th>번호</th>
                <th>제목</th>
                <th>작성일</th>
                <th>작성자</th>
                <th>답변상태</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for question in question_list %}
            <tr>
                <td>{{question.id}}</td>
                <td><a href="{% url 'qna:detail' question.id %}"> {{question.title}}</td>
                <td>{{question.updated_at|date:'Y.m.d'}}</td>
                <td>{{question.user}}</td>
                <td class='field-status'>
                    {% if question.status %}
                        <img src="/static/admin/img/icon-yes.svg">
                    {% else %}
                        <img src="/static/admin/img/icon-no.svg">
                    {% endif %}
                </td>
                {% if request.user == question.user %}
                    <td>
                        <form action="{% url 'qna:update' question.id %}" method="get">
                            <input type="submit" value="수정">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'qna:remove' question.id %}"" method="post">
                            <input type="submit" value="삭제">
                            {% csrf_token %}
                        </form>
                    </td>      
                {% else%}
                    <td></td>
                    <td></td>          
                {%endif%}
               
            </tr>
        {% endfor%}
        </tbody>
    </table>
{% endblock %}

dev/django_onlineshop/qna/templates/qna/qna_add.html
{% extends "base.html" %}

{% block title %}
    Q&A
{% endblock %}

{% block content %}
    <h1>Q&A</h1>
    <div class="qna">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="글등록">
    </form>
    </div>

{% endblock %}

dev/django_onlineshop/qna/templates/qna/question_form.html
{% extends "base.html" %}

{% block title %}
    Q&A
{% endblock %}

{% block content %}
    <h1>Q&A</h1>
    <div id="qna">
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="전송">
        </form>
    </div>

{% endblock %}