dev/myproject/article/urls.py
from django.urls import path
from django.views.generic import ListView
from . import views
from .models import Article

app_name = 'article'
urlpatterns = [
    # path('', ListView.as_view(model=Article), name='list'),
    # path('', views.article_list, name='list'),
    path('', views.MyListView.as_view(), name='list'),
    path('<id>/detail/', views.detail, name='detail'),
    path('new/', views.article_new, name='new'),
    path('<pk>/edit/', views.article_edit, name='edit'),
    path('<pk>/delete/', views.article_delete, name='delete'),
]

dev/myproject/blog/urls.py
from django.urls import path, register_converter
from . import views
from .converters import CodeConverter

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='list'),
    path('<int:post_id>/', views.detail),
    # path('archives/<dddd:code>/', views.blog_code),
    path('json/', views.json_test),
    path('file/', views.excel_download),
    path('redirect/', views.get_redirect),
]

dev/myproject/myproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('article/', include('article.urls')),
    # path('mytest/', include('mytest.urls')),
    path('book/', include('book.urls')),
    path('accounts/', include('accounts.urls')),
    # path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dev/myproject/myproject/templates/layout.html
{% load static %}

<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>{% block title %}TheBrains Article{% endblock %}</title>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<style>
    html {position: relative; min-height: 100%}
    body{margin-bottom: 60px}
    #page-footer{
        position: absolute;
        bottom: 0;
        width:100%;
        height: 60;
        line-height: 60px;
        background-color: #f5f5f5;
    }
</style>
<script src="//code.jquery.com/jquery-2.2.4.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'article:list' %}"><img src="{% static 'main_logo.png' %}"></a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'article:list' %}">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_anonymous %}
                        {% comment %} <li><a href="#">{{today}}</a></li> {% endcomment %}
                        <li><a href="{% url 'signup' %}">회원가입</a></li>
                        <li><a href="{% url 'login' %}?next={{request.path}}">로그인</a></li>
                    {% else %}  
                        <li><a href="{% url 'profile' %}">{{user}}</a> </li>
                        <li><a href="{% url 'logout' %}?next={{request.path}}">로그아웃</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% block content %}
                {% endblock %}
            </div>            
        </div>
    </div>

    <div id="page-footer">
        <div class="container">
            <p class="text-muted">
                Copyright © 2003 TheBrains All Right Reserved
            </p>
        </div>
    </div>
</body>
</html>

dev/myproject/myproject/templates/root.html
<h1>Root Page</h1>