dev/django_onlineshop/cart/urls.py
from django.urls import path
from . import views

app_name ='cart'
urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<product_id>/',views.cart_add,name='cart_add'),
    path('remove/<product_id>/',views.cart_remove,name='cart_remove'),
    path('clear/',views.cart_clear,name='cart_clear'),

]

dev/django_onlineshop/coupons/urls.py
from django.urls import path
from . import views

app_name ='coupons'
urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

dev/django_onlineshop/mysite/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('shop:product_list'),
         name='root'),  # 간단한 함수일 때, lamda식으로 표현
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('coupons/', include('coupons.urls')),
    path('orders/', include('orders.urls')),
    path('qna/', include('qna.urls')),
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.insert(0, path('__debug__/', include(debug_toolbar.urls)))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dev/django_onlineshop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/',views.order_create,name='order_create'),
    path('admin/order/<order_id>/',views.admin_order_detail,name='admin_order_detail'),
]

dev/django_onlineshop/qna/urls.py
from django.urls import path
from django.urls.base import reverse_lazy
from django.views.generic import UpdateView, DeleteView
from . import views
from .models import Question, Answer
from .forms import QuestionForm

app_name = 'qna'
urlpatterns = [
    path('add/', views.qna_add, name='add'),
    path('<pk>/update/', UpdateView.as_view(model=Question, form_class=QuestionForm), name='update'),
    path('<pk>/delete/', DeleteView.as_view(model=Question, success_url=reverse_lazy('qna:list')), name='remove'),
    path('', views.qna_list, name='list'),
    path('<id>/', views.qna_detail, name='detail'),
]

dev/django_onlineshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label='수량',  choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

dev/django_onlineshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm


def cart_detail(request):
    cart = Cart(request)
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html',{'cart':cart,'coupon_apply_form':coupon_apply_form})   

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['update'])

    return redirect('cart:cart_detail')

def cart_remove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')    

dev/django_onlineshop/cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th></th>
                <th>상품명</th>
                <th>수량</th>
                <th>삭제</th>
                <th class="text-right">단가</th>                
                <th class="text-right">금액</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{ item.override_quantity_form.quantity }}
                        {{ item.override_quantity_form.update }}
                        <input type="submit" value="수정">
                        {% csrf_token %}
                    </form>
                </td>
                <td>
                    <form action="{% url 'cart:cart_remove' product.id %}"" method="post">
                        <input type="submit" value="삭제">
                        {% csrf_token %}
                    </form>
                </td>
                <td class="num">{{ item.price|intcomma}}원</td>
                <td class="num">{{ item.total_price|intcomma}}원</td>
            </tr>
            {% endwith %}
        {% endfor %}

        {% if cart.has_coupon %}
            <tr class="subtotal">
                <td>Subtotal</td>
                <td colspan="4"></td>
                <td class="num">{{ cart.get_total_price|intcomma }}</td>
            </tr>
            <tr>
                    <td>"{{ cart.coupon.code }}" coupon ({{ cart.coupon.discount }}% off)</td>
                <td colspan="4"></td>
                <td class="num neg">- {{ cart.get_discount|intcomma }}</td>
            </tr>
        {% endif %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price_after_discount|intcomma}}원</td>
        </tr>
        </tbody>
    </table>
    
    <form action="{% url 'coupons:apply' %}" method="post">
        {{ coupon_apply_form }}
        <input type="submit" value="적용">
        {% csrf_token %}
    </form>
    <p class="text-right">
        <a href="{% url 'shop:product_list' %}" class="button light">쇼핑 계속하기</a>
        <a href="{% url 'orders:order_create' %}" class="button">주문하기</a>
        <a href="{% url 'cart:cart_clear' %}" class="button light">장바구니 비우기</a>
    </p>
{% endblock %}